Birthdays function
abond13/Vault13Ware pull request #19
Opened 2024-03-13 18:37 UTC by pokotilobogdan

`Birthday(datetime.date)` -> `Birthday(Field)`. 
Reworked `get_birthdays` function

2024-03-13 20:01 UTC, Virus1908 requested changes

2024-03-13 20:01 UTC, Virus1908 commented on get_birthdays_project.py
> +
можна видалити

2024-03-13 20:01 UTC, Virus1908 commented on get_birthdays_project.py
> +        for day in get_days(today, quantity):
цей код неефктивний, оскільки має складність o(n^2)
як на мене найкращий варіант зробити так, як пропонували в домашній роботі:
```
        next_birthday = birthday_date.replace(year=today.year)
        if next_birthday < today:
            next_birthday = birthday_date.replace(year=today.year + 1)
        delta_days = (next_birthday - today).days
        if delta_days >= quantity:
            continue
```

2024-03-13 20:01 UTC, Virus1908 commented on get_birthdays_project.py
> +                    calendar[key_outer] = {}
якщо календар буде `defaultdict(dict)`, то не треба буде ловити помилки

2024-03-13 20:01 UTC, Virus1908 commented on get_birthdays_project.py
> +                        calendar[key_outer][key_inner] = [name]
або навіть краще defaultdict(lambda: defaultdict(list))

2024-03-13 20:06 UTC, pokotilobogdan commented on get_birthdays_project.py
> +
Або я запушив прям перед тим як видалив, або щось десь не так. В будь-якому випадку, локально в мене цього коду вже немає, і з наступним пушем повинно бути норм

2024-03-13 21:04 UTC, blacklightsun commented on get_birthdays_project.py
> +        for day in get_days(today, quantity):
у мене в ДЗ ця частина була така:

```
day_delta = (birthday_this_year - today_date).days # days from today to birthday
            if 0 <= day_delta and day_delta < BIRTHDATE_SCOPE:
```

якщо цікаво - функція з ДЗ повністю:

```
def get_birthdays_per_week(self):
        '''
        This method print a list of contacts with birthdays today and next 6 days.
        If birthday will be on weekends (Saturday, Sunday) then birthday message would move
        on next Monday.
        '''

        if len(self.data) == 0:
            print('\nNobody is in your contact list. (((\n')
            return

        BIRTHDATE_SCOPE = 7 # today and next 6 days
        WEEKENDS = (5, 6) # 5, 6 = saturday, sunday
        today_date = datetime.today().date()

        birthdays_dict = dict()
        for record in self.data.values():

            if record.birthday is not None: # checking for empty birthday
                birthday_this_year = record.birthday.value.date().replace(year=today_date.year)
            else:
                break

            weekday = birthday_this_year.weekday()
            if weekday in WEEKENDS: 
                birthday_this_year = birthday_this_year + timedelta(days=(7 - weekday)) # move to Monday

            day_delta = (birthday_this_year - today_date).days # days from today to birthday
            if 0 <= day_delta and day_delta < BIRTHDATE_SCOPE:

                name = record.name.value

                if birthday_this_year not in birthdays_dict:
                    birthdays_dict[birthday_this_year] = name + ", " # for first date in dict
                else:
                    birthdays_dict[birthday_this_year] += name + ", " # for second and next dates in dict

        days_list = [i for i in birthdays_dict.keys()]

        if len(days_list) == 0:
            print(f"\nNo one celebrates their birthday in next {BIRTHDATE_SCOPE} days. (((\nThrow a party for yourself!!!\n")
            return

        days_list.sort()

        print_text = f"\nBirthdays in next {BIRTHDATE_SCOPE} days:\n-------------------------\n"

        for day in days_list:
            print_text += f"{str(day.strftime('%A'))+":":<12} {birthdays_dict[day].rstrip(', ')}\n"

        print(print_text)
```

2024-03-14 14:30 UTC, pokotilobogdan commented
Переробив з Birthdays(datetime.date) на Birthdays(Field). Все ж додав атрібути об'єкту day, month, year.

Функція get_birthdays перероблена поки лише щоб працювати в цілому. Складність з O(n^2) на O(n) планую переробити далі.

2024-03-14 14:35 UTC, pokotilobogdan commented on get_birthdays_project.py
> +# def get_birthdays(records: AddressBook, quantity: int):
Забув видалити з цього файла функцію, упс.

Імпортувати функцію з файлу не вийшло, бо виходив циклічний імпорт. Тому переніс функцію get-birthdays прямо до класу AddressBook

2024-03-14 16:00 UTC, pokotilobogdan commented on get_birthdays_project.py
> +                    calendar[key_outer] = {}
Я не впевнений, що можу так зробити, бо створив окремий клас `DictSortable(UserDict)`, щоб мати змогу сортувати словник по значенням ключів (це шоб дні народження виводились в правильній послідовності). Тому я не дуже розумію, чи можна буде поєднати `UserDict` та `defaultdict(dict)`

2024-03-14 17:28 UTC, pokotilobogdan commented on classes.py
>          except ValueError as exception:
Не впевнений, що ця частина коду має сенс, бо тепер немає насправді перевірки по datetime.

2024-03-14 19:02 UTC, abond13 approved these changes

2024-03-14 19:04 UTC, Virus1908 approved these changes

2024-03-14 19:04 UTC, merged